/**
 * _daily.js — which challenge is today's.
 *
 * THE RULE: the same challenge for everyone, derived from the date alone.
 *
 * Nothing is stored, nothing is scheduled, and no job has to run at midnight.
 * Given a date this returns the challenge, so yesterday's and tomorrow's are
 * equally computable — which is what makes a streak checkable, a share link
 * honest, and a missed day recoverable rather than lost.
 *
 * Two decisions, made differently on purpose:
 *
 *   the game    ROTATES through the five in order. A player who comes back
 *               daily gets variety by construction, not by luck. Hashing it
 *               would give three Higher or Lowers in a week often enough to
 *               notice.
 *
 *   the scope   HASHED from the date. Rotation through 399 scopes would take
 *               over a year to repeat and would march through the list in a
 *               visible order; a hash looks like a choice.
 *
 * The pool is generated by scripts/daily/pool.js and every scope in it has
 * earned a place on depth, spread and history. See that file for why.
 */

const POOL = require('../../data/daily/pool.json');
const teams = require('./_teams');

const DAY_MS = 86_400_000;

/**
 * The five games, in the order a week runs through them.
 *
 * Bullseye is absent: it takes a category id of its own shape rather than a
 * scope id, so wiring it in is a separate piece of work rather than a line in
 * this list.
 */
const GAMES = [
  { key: 'hol',    name: 'Higher or Lower', path: '/games/hol.html',
    verb: 'Which player has more appearances?' },
  { key: 'whoami', name: 'Who Am I?',       path: '/games/whoami.html',
    verb: 'Guess the player from five clues.' },
  { key: 'alpha',  name: 'Player Alphabet', path: '/games/alpha.html',
    verb: 'Name a player for every letter.' },
  { key: 'quiz',   name: 'Trivia Quiz',     path: '/games/quiz.html',
    verb: 'Ten questions from this club’s record.' },
  { key: 'xi',     name: 'Starting XI',     path: '/games/xi.html',
    verb: 'Build the strongest eleven you can.' },
];

/** YYYY-MM-DD in UTC. One day boundary worldwide, so the challenge matches. */
function today() {
  return new Date().toISOString().slice(0, 10);
}

function isDate(s) {
  return typeof s === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(s) &&
         !Number.isNaN(Date.parse(`${s}T00:00:00Z`));
}

const dayNumber = (dateStr) => Math.floor(Date.parse(`${dateStr}T00:00:00Z`) / DAY_MS);

/** FNV-1a. Small, stable, and identical in every language this may be ported to. */
function hash(str) {
  let h = 2166136261;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

/**
 * Today's challenge, or any given day's.
 *
 * The scope is re-drawn if it lands on the same club as yesterday. Two
 * consecutive Arsenal days is the one outcome a hash produces that a person
 * reads as broken rather than random, and it costs one line to prevent.
 */
function challengeFor(dateStr) {
  const date = isDate(dateStr) ? dateStr : today();
  const n = dayNumber(date);
  const game = GAMES[((n % GAMES.length) + GAMES.length) % GAMES.length];

  const pool = POOL.scopes;
  let idx = hash(`ts-daily|${date}`) % pool.length;

  const yesterday = new Date(Date.parse(`${date}T00:00:00Z`) - DAY_MS).toISOString().slice(0, 10);
  const prev = pool[hash(`ts-daily|${yesterday}`) % pool.length];
  if (prev && pool[idx].slug === prev.slug) idx = (idx + 1) % pool.length;

  const scope = pool[idx];
  const team = teams.bySlug(scope.slug);

  return {
    date,
    day: n,
    game: { key: game.key, name: game.name, path: game.path, blurb: game.verb },
    scope: {
      id: scope.id,
      team: scope.team,
      slug: scope.slug,
      // null means the scope covers everything the club has played.
      competition: scope.competition,
      players: scope.players,
      seasons: scope.seasons,
    },
    teamPage: team ? `/teams/${team.slug}/` : null,
    // Where "play today's challenge" goes. daily=<date> is what the game hands
    // back so a result can be filed against the right day.
    url: `${game.path}?scope=${encodeURIComponent(scope.id)}&play=1&daily=${date}`,
    label: scope.competition
      ? `${scope.team} in ${scope.competition}`
      : `${scope.team}, all competitions`,
  };
}

module.exports = { challengeFor, today, isDate, GAMES, hash, poolSize: POOL.scopes.length };
